name: 'Finish new deployment'
inputs:
  token:
    description: 'Github repository token'
  deployment_id:
    description: "Id of a deployment to finish"
  required_jobs:
    description: "List of jobs which cannot result in a failure. In a form of $_{{ toJson(needs) }}"
runs:
  using: 'node12'
  main: 'index.js'
