name: 'Start new deployment'
inputs:
  token:
    description: 'Github repository token'
  ref:
    description: 'Git ref'
  environment:
    description: 'Name for the target deployment environment, which can be changed when setting a deploy status.'
  required_contexts:
    description: 'The status contexts to verify against commit status checks. If you omit this parameter, GitHub verifies all unique contexts before creating a deployment. To bypass checking entirely, pass an empty array. Defaults to all unique contexts.'
outputs:
  deployment_id:
    description: "Id of the new deployment"
runs:
  using: 'node12'
  main: 'index.js'
